# Generated by Django 2.2.7 on 2020-08-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200831_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpost',
            name='phone',
            field=models.CharField(default='', max_length=70),
        ),
    ]
