# Generated by Django 2.2.7 on 2020-08-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_sellpost_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellpost',
            name='pub_date',
        ),
    ]
