# Generated by Django 2.2.7 on 2020-08-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_remove_sellpost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellpost',
            name='image',
            field=models.ImageField(default='', upload_to='media/seller/images'),
        ),
    ]
