# Generated by Django 2.2.7 on 2020-08-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20200831_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellpost',
            name='image',
            field=models.ImageField(default='', upload_to='seller/images'),
        ),
    ]
