# Generated by Django 2.2.7 on 2020-09-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20200831_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellpost',
            name='image',
            field=models.FileField(default='', upload_to='seller/images'),
        ),
    ]
