# Generated by Django 2.2.7 on 2020-09-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20200901_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellpost',
            name='image',
            field=models.ImageField(default='', upload_to='seller/images'),
        ),
    ]
