# Generated by Django 3.0.2 on 2020-01-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0003_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
