# Generated by Django 3.0.2 on 2020-01-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0004_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
